name: Drift Prod

on:
  workflow_dispatch:

jobs:
  prod:
    uses: ./.github/workflows/terraform-core.yml
    with:
      environment: prod
      region: ap-south-1
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}    