name: Drift Prod

on:
  workflow_dispatch:

jobs:
  prod:
    uses: ./.github/workflows/terraform-core.yml
    with:
      environment: prod
      region: ap-south-1
      auto_apply: false
    secrets: inherit